/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mitac_vibrator_RTC */

#ifndef _Included_com_mitac_vibrator_RTC
#define _Included_com_mitac_vibrator_RTC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mitac_vibrator_RTC
 * Method:    getTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mitac_vibrator_RTC_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
